#!/usr/bin/env php
#
# The MIT License (MIT)
# 
# Copyright (c) 2011-2015 BitPay
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
<?php
/**
 * This script will package up the plugin for distribution
 */
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
date_default_timezone_set('America/New_York'); // Main Office is in Eastern Timezone

$version    = '1.x';
$distDir    = __DIR__ . '/../build/dist';
$tmpDistDir = $distDir . '/tmp';
$distFile   = $distDir . '/Bitpay-' . $version;

require_once __DIR__ . '/../vendor/autoload.php';

$filesystem = new \Symfony\Component\Filesystem\Filesystem();
$filesystem->mirror('bitpay/', sprintf('%s/bitpay/', $tmpDistDir));
$filesystem->mirror('includes/', sprintf('%s/includes/', $tmpDistDir));
$filesystem->copy('LICENSE', sprintf('%s/LICENSE', $tmpDistDir));
$filesystem->copy('README.md', sprintf('%s/README.md', $tmpDistDir));

$filesystem->remove($distFile.'.zip');
$filesystem->remove($distFile.'.tgz');

$process = new \Symfony\Component\Process\Process(
    sprintf('cd %s; zip -r %s .', $tmpDistDir, $distFile.'.zip')
);
$process->run();
$process = new \Symfony\Component\Process\Process(
    sprintf('cd %s; tar -czf %s *', $tmpDistDir, $distFile.'.tgz')
);
$process->run();

// Cleanup
$filesystem->remove($tmpDistDir);
